spring:
  application:
    name: sellora
  datasource:
    url: jdbc:postgresql://localhost:5432/sellora
    username: sellora
    password: sellora
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: localhost
      port: 6379
  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  security:
    user:
      name: disabled
      password: disabled
    jwt:
      secret: NYyi1S20GJufEk8aKx3eicgpa789tq9N
      access-token-expiration: 1800000
      refresh-token-expiration: 604800000

server:
  port: 8080
  servlet:
    context-path: /sellora/api

logging:
  level:
    root: INFO
    kz.sellora: DEBUG
    org.hibernate.orm.connections.pooling: error
    org.flywaydb: DEBUG
